Plot.ly is *DEAD*! Long live chart.js!
Got rid of plot.ly, though there may still be some remnants left. Swapped to chart.js. Not quite working, but we're so close that I can taste it. did yarn stuff, still not finding module chart.js (ERROR in src/app/charts/charts.component.ts(6,24): error TS2307: Cannot find module 'chart.js'.)

As soon as we get past this bump, we home free.

Must ask Nick about setup stuff.

Credit to Francisco for guidance in the chart.js setup thus far. taught what he could remember of what Nick taught him.